version: '3.8'

services:
  nextjs:
    build: .
    container_name: nextjs-motorock
    restart: always
    ports:
      - '3000:3000'
    environment:
      MONGODB_URI: ${MONGODB_URI}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
      NEXT_PUBLIC_TOKEN_API_RUC_DNI: ${NEXT_PUBLIC_TOKEN_API_RUC_DNI}
      NEXT_PUBLIC_API_RUC_DNI_URL: ${NEXT_PUBLIC_API_RUC_DNI_URL}
    volumes:
      - .:/app
