version: '3.8'  # (opcional, pero recomendable incluirlo)

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: qweasdzxc
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db  # Volumen para persistir datos de MongoDB

  nextjs:
    build: .
    container_name: nextjs-motorock
    restart: always
    ports:
      - '3000:3000'
    environment:
      MONGODB_URI: mongodb://admin:qweasdzxc@mongodb:27017/motorock?authSource=admin
      NEXTAUTH_URL: http://localhost:3000
      NEXTAUTH_SECRET: N1ouTYi6isl2sz6
      NEXT_PUBLIC_API_URL: http://localhost:3000/api
      NEXT_TOKEN_SUNAT: apis-token-11180.sMCjVvCzDCLfbeIeYfFTPX1uuypmvEEj
    depends_on:
      - mongodb
    volumes:
      - .:/app  # Montar el código fuente desde la raíz en /app del contenedor

volumes:
  mongo-data:  # Definición del volumen
