export const dataTest = [
  {
    nombres: 'Mr. Leona Hagenes',
    apellidos: 'Dixie Gulgowski',
    dni: 49,
    celular: 37,
    rol: 'administrador',
    id: '1',
  },
  {
    nombres: 'Nathaniel Reynolds II',
    apellidos: 'Mamie Marvin',
    dni: 83,
    celular: 20,
    rol: 'administrador',
    id: '2',
  },
  {
    nombres: 'Kim Feil',
    apellidos: 'Yvonne Terry',
    dni: 91,
    celular: 37,
    rol: 'administrador',
    id: '3',
  },
  {
    nombres: 'Patty Murphy',
    apellidos: 'Vera Johns',
    dni: 82,
    celular: 19,
    rol: 'administrador',
    id: '4',
  },
  {
    nombres: 'Francisco Murazik II',
    apellidos: 'Dr. Edmund Farrell',
    dni: 79,
    celular: 75,
    rol: 'administrador',
    id: '5',
  },
  {
    nombres: 'Manuel McCullough',
    apellidos: 'Pearl Dickinson',
    dni: 16,
    celular: 27,
    rol: 'administrador',
    id: '6',
  },
  {
    nombres: 'Peter Fadel',
    apellidos: 'Darren Hauck',
    dni: 10,
    celular: 55,
    rol: 'administrador',
    id: '7',
  },
  {
    nombres: 'Antonia Brown',
    apellidos: 'Madeline Wilkinson',
    dni: 38,
    celular: 93,
    rol: 'administrador',
    id: '8',
  },
  {
    nombres: 'Ora Flatley MD',
    apellidos: 'Patsy Denesik',
    dni: 10,
    celular: 39,
    rol: 'administrador',
    id: '9',
  },
  {
    nombres: 'Kim Sawayn III',
    apellidos: 'Allan Farrell',
    dni: 53,
    celular: 88,
    rol: 'administrador',
    id: '10',
  },
  {
    nombres: 'Roger Hammes',
    apellidos: 'Doreen Bahringer',
    dni: 68,
    celular: 26,
    rol: 'administrador',
    id: '11',
  },
  {
    nombres: 'Amanda Effertz',
    apellidos: 'Flora Hoppe',
    dni: 85,
    celular: 83,
    rol: 'administrador',
    id: '12',
  },
  {
    nombres: 'Rogelio Jerde',
    apellidos: 'Jean Bechtelar',
    dni: 34,
    celular: 88,
    rol: 'administrador',
    id: '13',
  },
  {
    nombres: 'Ryan Labadie Jr.',
    apellidos: 'Jesse Block',
    dni: 35,
    celular: 91,
    rol: 'administrador',
    id: '14',
  },
  {
    nombres: 'Noah Lind',
    apellidos: 'Olga Hackett Sr.',
    dni: 42,
    celular: 29,
    rol: 'administrador',
    id: '15',
  },
  {
    nombres: 'Ms. Judith Strosin',
    apellidos: 'Israel Reichel V',
    dni: 61,
    celular: 67,
    rol: 'administrador',
    id: '16',
  },
  {
    nombres: 'Mrs. Timmy Rath',
    apellidos: 'Miss Jake Skiles',
    dni: 44,
    celular: 32,
    rol: 'administrador',
    id: '17',
  },
  {
    nombres: 'Courtney Leffler',
    apellidos: 'Jaime Collier',
    dni: 81,
    celular: 2,
    rol: 'administrador',
    id: '18',
  },
  {
    nombres: 'Julio Lemke',
    apellidos: 'Dr. Eula Kihn',
    dni: 64,
    celular: 23,
    rol: 'administrador',
    id: '19',
  },
  {
    nombres: 'Shelia Lynch',
    apellidos: 'Wendell Jenkins',
    dni: 30,
    celular: 76,
    rol: 'administrador',
    id: '20',
  },
  {
    nombres: 'Connie Leannon',
    apellidos: 'Shannon Smith',
    dni: 38,
    celular: 46,
    rol: 'administrador',
    id: '21',
  },
  {
    nombres: 'Mona Watsica',
    apellidos: 'Eula Feil',
    dni: 38,
    celular: 17,
    rol: 'administrador',
    id: '22',
  },
  {
    nombres: 'Roland Wilkinson',
    apellidos: 'Iris Beatty',
    dni: 76,
    celular: 34,
    rol: 'administrador',
    id: '23',
  },
  {
    nombres: 'Mr. Georgia Turcotte IV',
    apellidos: 'Martha DuBuque',
    dni: 87,
    celular: 79,
    rol: 'administrador',
    id: '24',
  },
  {
    nombres: 'Minnie Kuphal',
    apellidos: 'Mr. Dana Cruickshank',
    dni: 74,
    celular: 34,
    rol: 'administrador',
    id: '25',
  },
  {
    nombres: "Edward D'Amore",
    apellidos: 'Don Lebsack',
    dni: 26,
    celular: 49,
    rol: 'administrador',
    id: '26',
  },
  {
    nombres: 'Lisa Krajcik',
    apellidos: 'Andy Harvey',
    dni: 23,
    celular: 87,
    rol: 'administrador',
    id: '27',
  },
  {
    nombres: 'Tiffany Larson MD',
    apellidos: 'Ernestine Thompson I',
    dni: 78,
    celular: 9,
    rol: 'administrador',
    id: '28',
  },
  {
    nombres: 'Mrs. Terrell Paucek',
    apellidos: 'Tyrone Mayert',
    dni: 9,
    celular: 28,
    rol: 'administrador',
    id: '29',
  },
  {
    nombres: 'Max Williamson',
    apellidos: 'Hannah Mohr DVM',
    dni: 95,
    celular: 11,
    rol: 'administrador',
    id: '30',
  },
  {
    nombres: 'Taylor Hackett DVM',
    apellidos: 'Guillermo Casper III',
    dni: 94,
    celular: 8,
    rol: 'administrador',
    id: '31',
  },
  {
    nombres: 'Jody Fritsch',
    apellidos: 'Marty Ernser',
    dni: 10,
    celular: 51,
    rol: 'administrador',
    id: '32',
  },
  {
    nombres: 'Joshua Kessler',
    apellidos: 'Ernestine Thompson',
    dni: 5,
    celular: 52,
    rol: 'administrador',
    id: '33',
  },
  {
    nombres: 'Guillermo Mills',
    apellidos: 'Elvira Effertz',
    dni: 54,
    celular: 43,
    rol: 'administrador',
    id: '34',
  },
  {
    nombres: 'Dave Tromp',
    apellidos: 'Christian Welch',
    dni: 12,
    celular: 10,
    rol: 'administrador',
    id: '35',
  },
  {
    nombres: 'Mr. Fred Kuphal',
    apellidos: 'Erika Paucek',
    dni: 26,
    celular: 15,
    rol: 'administrador',
    id: '36',
  },
  {
    nombres: 'Gilberto Powlowski DDS',
    apellidos: 'Wilma Flatley',
    dni: 89,
    celular: 87,
    rol: 'administrador',
    id: '37',
  },
  {
    nombres: 'Harold Ryan I',
    apellidos: 'Aubrey Halvorson III',
    dni: 88,
    celular: 42,
    rol: 'administrador',
    id: '38',
  },
  {
    nombres: 'Alan Kris',
    apellidos: 'Deborah Prosacco',
    dni: 18,
    celular: 98,
    rol: 'administrador',
    id: '39',
  },
  {
    nombres: 'Amos Gutkowski',
    apellidos: 'Megan Breitenberg',
    dni: 8,
    celular: 58,
    rol: 'administrador',
    id: '40',
  },
  {
    nombres: 'Rosie Spinka',
    apellidos: 'Miss Nelson McGlynn',
    dni: 45,
    celular: 45,
    rol: 'administrador',
    id: '41',
  },
  {
    nombres: 'Sandy Kovacek',
    apellidos: 'Phillip Predovic',
    dni: 13,
    celular: 12,
    rol: 'administrador',
    id: '42',
  },
  {
    nombres: 'Lena Orn',
    apellidos: 'Margarita Morissette',
    dni: 49,
    celular: 97,
    rol: 'administrador',
    id: '43',
  },
  {
    nombres: 'Lisa Stroman',
    apellidos: 'Cheryl Wolf',
    dni: 22,
    celular: 53,
    rol: 'administrador',
    id: '44',
  },
  {
    nombres: 'Vanessa Schroeder',
    apellidos: 'Roderick Schamberger',
    dni: 35,
    celular: 89,
    rol: 'administrador',
    id: '45',
  },
  {
    nombres: 'Cristina Conn',
    apellidos: 'Kathy Koss',
    dni: 61,
    celular: 67,
    rol: 'administrador',
    id: '46',
  },
  {
    nombres: 'Tomas Waelchi',
    apellidos: 'Merle Heathcote',
    dni: 91,
    celular: 81,
    rol: 'administrador',
    id: '47',
  },
  {
    nombres: 'Roger Franey',
    apellidos: 'Ms. Lester Abernathy',
    dni: 65,
    celular: 57,
    rol: 'administrador',
    id: '48',
  },
  {
    nombres: 'Miss Troy Wunsch',
    apellidos: 'Wilbert Murazik Sr.',
    dni: 15,
    celular: 0,
    rol: 'administrador',
    id: '49',
  },
  {
    nombres: 'Jake DuBuque',
    apellidos: 'Velma Wisozk',
    dni: 62,
    celular: 20,
    rol: 'administrador',
    id: '50',
  },
  {
    nombres: 'Sheila Quigley',
    apellidos: 'Mrs. Roland Konopelski',
    dni: 50,
    celular: 38,
    rol: 'administrador',
    id: '51',
  },
  {
    nombres: 'Dr. Rosemarie Jones',
    apellidos: 'Miguel Kuhic',
    dni: 74,
    celular: 24,
    rol: 'administrador',
    id: '52',
  },
  {
    nombres: 'Ellen McGlynn PhD',
    apellidos: 'Mr. Amanda Johnston',
    dni: 31,
    celular: 71,
    rol: 'administrador',
    id: '53',
  },
  {
    nombres: 'Lee Monahan',
    apellidos: 'Jonathon Champlin',
    dni: 13,
    celular: 80,
    rol: 'administrador',
    id: '54',
  },
  {
    nombres: 'Ellen Dickens',
    apellidos: 'Shelia Paucek',
    dni: 85,
    celular: 74,
    rol: 'administrador',
    id: '55',
  },
  {
    nombres: 'Heidi Vandervort',
    apellidos: 'Ms. Boyd Oberbrunner',
    dni: 41,
    celular: 70,
    rol: 'administrador',
    id: '56',
  },
  {
    nombres: 'Brendan Paucek',
    apellidos: 'Elbert Fay',
    dni: 3,
    celular: 71,
    rol: 'administrador',
    id: '57',
  },
  {
    nombres: 'Connie Wintheiser',
    apellidos: 'Sheldon Parker',
    dni: 81,
    celular: 75,
    rol: 'administrador',
    id: '58',
  },
  {
    nombres: 'Hattie Heller',
    apellidos: 'Darren Price',
    dni: 11,
    celular: 52,
    rol: 'administrador',
    id: '59',
  },
  {
    nombres: 'Chelsea Stroman',
    apellidos: 'Lana Stark',
    dni: 42,
    celular: 92,
    rol: 'administrador',
    id: '60',
  },
];
